spring:
  application:
    name: springboot-swagger-example-admin-server
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8088/pet-store/v1
        instance:
          prefer-ip: true

server:
  servlet:
    context-path: /pet-store/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, ODD, EVEN, UP
  info:
    git:
      mode: full
