server:
  port: 8088

logging:
  level:
    org.springframework: ERROR
    org.apache.catalina: ERROR
    springfox.documentation.spring.web: ERROR
    it.davidgreco.examples.springboot_swagger_example: ERROR