apiVersion: v1
kind: Service
metadata:
  name: springboot-swagger-example-admin-server
  labels:
    app: springboot-swagger-example-admin-server
spec:
  type: NodePort
  ports:
  - port: 8088
    protocol: TCP
    name: http
  selector:
    app: springboot-swagger-example-admin-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springboot-swagger-example-admin-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-swagger-example-admin-server
    spec:
      containers:
      - name: springboot-swagger-example-admin-server
        image: 10.98.74.120:5000/springboot-swagger-example-admin-server:1.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 8088
        securityContext:
          privileged: false
#          runAsUser:
        volumeMounts:
         - name: springboot-swagger-example-admin-server
           mountPath: "/app/resources/application.yaml"
           subPath: "application.yaml"
           readOnly: true
         - name: springboot-swagger-example-admin-server
           mountPath: "/app/resources/application-dev.yaml"
           subPath: "application-dev.yaml"
           readOnly: true
         - name: springboot-swagger-example-admin-server
           mountPath: "/app/resources/application-prod.yaml"
           subPath: "application-prod.yaml"
           readOnly: true
         - name: springboot-swagger-example-admin-server
           mountPath: "/app/resources/logback-spring.xml"
           subPath: "logback-spring.xml"
           readOnly: true
        env:
         - name: SPRING_APPLICATION_JSON
           value: '{"spring": {"profiles": {"active": "prod"}}}'
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: springboot-swagger-example-admin-server
          secret:
            secretName: springboot-swagger-example-admin-server
            items:
            - key: application.yaml
              path: application.yaml
            - key: application-dev.yaml
              path: application-dev.yaml
            - key: application-prod.yaml
              path: application-prod.yaml
            - key: logback-spring.xml
              path: logback-spring.xml